export const permissionsNames = {
  addUser: 'addUser',
  updateUser: 'updateUser',
  deleteUser: 'deleteUser',
  exportUsers: 'exportUsers',
  addRoute: 'addRoute',
  updateRoute: 'updateRoute',
  deleteRoute: 'deleteRoute',
  addGov: 'addGov',
  updateGov: 'updateGov',
  deleteGov: 'deleteGov',
  exportGovs: 'exportGovs',
  addCity: 'addCity',
  updateCity: 'updateCity',
  deleteCity: 'deleteCity',
  exportCities: 'exportCities',
};
